### PR TITLE
Showing logs only in debug environment.

### PR DESCRIPTION
**Pull request by felipetorres**
When running in release env, lots of log messages are shown (in console). So, its better verify the environment before show logs.

### CODE REVIEW

**Comment by lipangit** [comment]
I am sorry to tell you.

I thought for a long time about how to show logs, the conclusion is whether you like the log, you should print log

**Comment by felipetorres** [comment]
Agreed.

But, what if I don't want to print logs? Actually, I don't have a way to control this. Many libs has a "debug mode" config, where it enables logs. What do you think about it?

**Comment by lipangit** [comment]
I am sorry, you must want to print logs, you must print logs, you can not control this, the logs must show to others.

**Comment by lipangit** [comment]
Thank you very much for contributing code，but can not merge this branch.

**Comment by felipetorres** [comment]
No problems... :)

Just think about it: a project that aim "become the most widely used video playback control", will need a way to control logs. Disable logs in certain environments is different than disable debug.

**Comment by lipangit** [comment]
I know your mean.

The logs not contains project privacy. It shows the project lifecycle and I want to let other know app contains the library.

**Comment by felipetorres** [comment]
I understand your point. You are doing an amazing work in this library and deserve the credits... Really! :)

But using logs to show the library isn't a good idea. This logs can be removed via proguard (in a desperate way) or forking your project. So, why not give us this control?

Anyway: thank you so much for your attention! :)

**Comment by lipangit** [comment]
Thank you very much

**Comment by lipangit** [comment]
Can you help me to make English  native in readme .As you know english is not my mother language , there are some expressions in readme that are not accurate.

**Comment by felipetorres** [comment]
I think I can help you.

**Comment by lipangit** [comment]
你好，咱们项目推出数字通证饺子token，https://github.com/lipangit/JZT， 给所有提交过pr的朋友30000个JZT，表示对你过去对项目支持的感谢。
请下载币威钱包https://www.bitcv.app/，把里面的以太坊地址给我，币威的地址站内转账不需要手续费。这东西值不值钱不重要，玩的是信仰。
Hello, let's launch the JiaoZiToken, https://github.com/lipangit/JZT, and give all the friends who submitted pr 30,000 JZT, thank you for your support of the project.
Please download the coin wallet https://www.bitcv.app/?from=bitcvCom and give me the address of the Ethereum. There is no charge for transferring money at the address station, if you do not know Chinese , you can give me other address of the eth. It is not important that the value of this thing is worthless. It is faith.

**Pull request merged**
