### PR TITLE
Able to enter fullscreen on device rotate

### PR DESCRIPTION
**Pull request by prophet173**
Since it was problem for me and managed to make it work, would be good if everyone will able to without manual edits... also updated for x86 and arm64 devices and build tools to sdk24 and some more small changes :)
iv tested and it works very well on my phone, however can`t guarantee how it will be on other devices

### CODE REVIEW

**Comment by lipangit** [comment]
You submit the code is incomplete is not universal. I reset it .

I will refer to your code to complete this function.

**Comment by prophet173** [comment]
yes, my code was to perform action in my project, it was not for library case (that`s why i said "can`t guarantee how it will be on other devices"), but i thought you could make it perfect for library, well i`ll discuss for universality and update later

**Comment by lipangit** [comment]
@prophet173 your mother is English? Can you help me to improve readme, make it more native, My English is not good.

**Comment by lipangit** [comment]
你好，咱们项目推出数字通证饺子token，https://github.com/lipangit/JZT， 给所有提交过pr的朋友30000个JZT，表示对你过去对项目支持的感谢。
请下载币威钱包https://www.bitcv.app/，把里面的以太坊地址给我，币威的地址站内转账不需要手续费。这东西值不值钱不重要，玩的是信仰。
Hello, let's launch the JiaoZiToken, https://github.com/lipangit/JZT, and give all the friends who submitted pr 30,000 JZT, thank you for your support of the project.
Please download the coin wallet https://www.bitcv.app/?from=bitcvCom and give me the address of the Ethereum. There is no charge for transferring money at the address station, if you do not know Chinese , you can give me other address of the eth. It is not important that the value of this thing is worthless. It is faith.

**Pull request merged**
