### PR TITLE
fix:全屏或小屏退出时不触发ON_QUIT_XXX事件的问题

### PR DESCRIPTION
**Pull request by yale8848**

### CODE REVIEW

**Comment by lipangit** [comment]
playOnThisJcvd()这函数里的第二行代码onEvent不工作吗，为什么放到后面的if里

**Comment by yale8848** [comment]
onEvent中的isCurrentJcvd的判断无效。应为JCVideoPlayerManager.getFirstFloor().playOnThisJcvd()中调用的是FirstFloor，JCVideoPlayerManager.getCurrentJcvd() == this不相等，getCurrentJcvd() 返回的是secondFloor，this是FirstFloor,你可以跑起来试试，ON_QUIT_TINYSCREEN，ON_QUIT_FULLSCREEN事件无法收到

**Comment by lipangit** [comment]
没错，我之前的代码确实有问题，你的代码能解决这个问题，多谢

**Comment by lipangit** [comment]
你好，咱们项目推出数字通证饺子token，https://github.com/lipangit/JZT， 给所有提交过pr的朋友30000个JZT，表示对你过去对项目支持的感谢。
请下载币威钱包https://www.bitcv.app/，把里面的以太坊地址给我，币威的地址站内转账不需要手续费。这东西值不值钱不重要，玩的是信仰。
Hello, let's launch the JiaoZiToken, https://github.com/lipangit/JZT, and give all the friends who submitted pr 30,000 JZT, thank you for your support of the project.
Please download the coin wallet https://www.bitcv.app/?from=bitcvCom and give me the address of the Ethereum. There is no charge for transferring money at the address station, if you do not know Chinese , you can give me other address of the eth. It is not important that the value of this thing is worthless. It is faith.

**Pull request merged**
